name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use your required Node.js version

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Build
        working-directory: ./app
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }} # Inject the secret here
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
          publish_branch: gh-page
